// 首次開啟網站、資料庫還是空的時候，會用這份資料自動建立初始行程。
// 之後大家在網站上做的新增/編輯/刪除都會存進 Supabase，不會再用到這份檔案。

export const seedDays = [
  {
    id: "day1",
    order_num: 1,
    date: "8/26（三）",
    title: "抵達名古屋 → 直奔高山",
    hotel: "高山｜JR 高山站東口周邊",
    items: [
      { period: "06:00", name: "🛬 中部國際機場 抵達", category: "transport", text: "", map_query: "中部国際空港" },
      { period: "07:43", name: "🚃 名鐵 → 名古屋站", category: "transport", text: "", map_query: "名古屋駅" },
      { period: "08:43", name: "🚄 JR特急 Hida → 高山", category: "transport", text: "車程約 2.5 小時，車上補眠", map_query: "高山駅" },
      { period: "11:00", name: "🧳 高山站・寄放行李", category: "transport", text: "", map_query: "高山駅" },
      { period: "11:30", name: "🐟 宮川朝市", category: "spot", text: "《冰菓》OP1 取景地", map_query: "宮川朝市" },
      { period: "13:00", name: "☕ 喫茶去 Bagpipe", category: "food", text: "點維也納咖啡重現「我好在意！」", map_query: "喫茶去 バグパイプ 高山" },
      { period: "14:30", name: "🏮 三町筋老街散策", category: "spot", text: "", map_query: "高山 三町筋" },
      { period: "15:30", name: "📚 高山市圖書館 煥章館", category: "spot", text: "", map_query: "高山市図書館 煥章館" },
      { period: "16:00", name: "⛩️ 日枝神社", category: "spot", text: "", map_query: "日枝神社 高山" },
      { period: "18:00", name: "🥩 飛驒牛燒肉／壽喜燒", category: "food", text: "晚餐", map_query: "飛騨牛 高山 焼肉" },
    ],
  },
  {
    id: "day2",
    order_num: 2,
    date: "8/27（四）",
    title: "《你的名字》巡禮 → 白川鄉 → 富山",
    hotel: "富山（第 1 晚）｜電鐵富山站／JR 富山站南口",
    items: [
      { period: "08:30", name: "🏫 斐太高校", category: "spot", text: "神山高校校門原型", map_query: "斐太高等学校" },
      { period: "09:30", name: "🚃 JR高山線 → 飛驒古川", category: "transport", text: "", map_query: "飛騨古川駅" },
      { period: "10:00", name: "🌊 瀨戶川與白壁土藏", category: "spot", text: "", map_query: "瀬戸川 白壁土蔵街" },
      { period: "10:45", name: "📚 飛驒市圖書館", category: "spot", text: "", map_query: "飛騨市図書館" },
      { period: "12:00", name: "🚌 濃飛巴士 → 白川鄉", category: "transport", text: "", map_query: "白川郷バスターミナル" },
      { period: "13:00", name: "🧳 白川鄉・寄放行李", category: "transport", text: "", map_query: "白川郷バスターミナル" },
      { period: "13:30", name: "🗻 城山展望台", category: "spot", text: "合掌村全景俯瞰", map_query: "城山天守閣展望台" },
      { period: "14:30", name: "🏡 和田家", category: "spot", text: "", map_query: "和田家 白川郷" },
      { period: "15:00", name: "🍢 飛驒牛串燒＋消暑冰品", category: "food", text: "", map_query: "白川郷合掌造り集落" },
      { period: "16:30", name: "🚌 巴士 → 富山", category: "transport", text: "", map_query: "富山駅" },
      { period: "18:30", name: "🌌 富岩運河環水公園", category: "spot", text: "世界最美星巴克・夜景", map_query: "富岩運河環水公園" },
    ],
  },
  {
    id: "day3",
    order_num: 3,
    date: "8/28（五）",
    title: "雨晴海岸 → 高岡 → 金澤",
    hotel: "富山（第 2 晚）",
    items: [
      { period: "08:00", name: "🚃 電車 → 雨晴海岸", category: "transport", text: "", map_query: "雨晴駅" },
      { period: "08:40", name: "🌅 雨晴海岸", category: "spot", text: "遠眺富山灣・立山連峰", map_query: "雨晴海岸" },
      { period: "10:00", name: "🚃 電車 → 高岡", category: "transport", text: "", map_query: "高岡駅" },
      { period: "10:30", name: "🏯 高岡古城公園", category: "spot", text: "水堀與綠意森林", map_query: "高岡古城公園" },
      { period: "11:00", name: "🔔 哆啦A夢散策路", category: "spot", text: "", map_query: "ドラえもんの散歩道 高岡" },
      { period: "12:00", name: "🚄 新幹線 → 金澤", category: "transport", text: "僅需 14 分鐘", map_query: "金沢駅" },
      { period: "12:30", name: "🦐 近江町市場", category: "food", text: "海鮮丼午餐", map_query: "近江町市場" },
      { period: "14:00", name: "🌸 兼六園", category: "spot", text: "", map_query: "兼六園" },
      { period: "15:30", name: "🏯 金澤城公園", category: "spot", text: "", map_query: "金沢城公園" },
      { period: "16:30", name: "🍦 東茶屋街", category: "spot", text: "金箔冰淇淋", map_query: "東茶屋街" },
      { period: "18:00", name: "🍽️ 金澤晚餐", category: "food", text: "", map_query: "金沢駅" },
      { period: "19:00", name: "🚄 北陸新幹線 → 富山", category: "transport", text: "約 20 分鐘", map_query: "富山駅" },
    ],
  },
  {
    id: "day4",
    order_num: 4,
    date: "8/29（六）",
    title: "穿越立山黑部阿爾卑斯路線 → 松本",
    hotel: "松本｜JR 松本站東口／Alpico 巴士總站周邊",
    items: [
      { period: "07:00", name: "🧳 富山站・行李託運", category: "transport", text: "當日行李直送松本飯店", map_query: "富山駅" },
      { period: "07:30", name: "🚇 富山地鐵 → 立山站", category: "transport", text: "", map_query: "立山駅" },
      { period: "08:00", name: "🚞 纜車 → 美女平", category: "transport", text: "", map_query: "美女平駅" },
      { period: "08:30", name: "🚌 高原巴士 → 室堂", category: "transport", text: "", map_query: "室堂駅" },
      { period: "09:30", name: "🥾 室堂・御庫裏池健行", category: "spot", text: "欣賞雄偉山景", map_query: "みくりが池" },
      { period: "12:00", name: "🚡 大觀峰空中纜車", category: "transport", text: "", map_query: "大観峰駅" },
      { period: "12:30", name: "🏔️ 黑部平", category: "spot", text: "", map_query: "黒部平駅" },
      { period: "13:30", name: "💦 黑部水壩", category: "spot", text: "震撼觀光放水", map_query: "黒部ダム" },
      { period: "15:00", name: "🚌 巴士 → 扇澤", category: "transport", text: "", map_query: "扇沢駅" },
      { period: "16:30", name: "🚃 轉乘 → 松本站", category: "transport", text: "", map_query: "松本駅" },
      { period: "18:00", name: "🏨 抵達松本・辦理入住", category: "hotel", text: "取回託運行李", map_query: "松本駅" },
    ],
  },
  {
    id: "day5",
    order_num: 5,
    date: "8/30（日）",
    title: "上高地絕景健行 → 諏訪湖溫泉",
    hotel: "諏訪湖／上諏訪溫泉｜上諏訪站前・諏訪湖畔",
    items: [
      { period: "07:30", name: "🚌 松本電鐵＋Alpico巴士 → 大正池", category: "transport", text: "", map_query: "大正池" },
      { period: "08:30", name: "🌲 大正池", category: "spot", text: "", map_query: "大正池" },
      { period: "09:15", name: "🍃 田代池", category: "spot", text: "", map_query: "田代池" },
      { period: "10:00", name: "🚶 梓川沿岸步道", category: "spot", text: "", map_query: "梓川 上高地" },
      { period: "11:30", name: "🌉 河童橋", category: "spot", text: "", map_query: "河童橋" },
      { period: "12:00", name: "🥧 河童橋午餐＋蘋果派", category: "food", text: "", map_query: "河童橋" },
      { period: "13:30", name: "🚌 巴士 → 松本", category: "transport", text: "", map_query: "松本駅" },
      { period: "15:00", name: "🚃 JR中央本線 → 上諏訪", category: "transport", text: "約 30 分鐘", map_query: "上諏訪駅" },
      { period: "16:00", name: "🌇 立石公園", category: "spot", text: "《你的名字》系守湖原型夕陽", map_query: "立石公園 諏訪湖" },
    ],
  },
  {
    id: "day6",
    order_num: 6,
    date: "8/31（一）",
    title: "諏訪湖散策 → 返回名古屋",
    hotel: "名古屋（第 1 晚）｜榮商圈或名古屋站周邊",
    items: [
      { period: "08:00", name: "🚶 諏訪湖畔散步＋足湯", category: "spot", text: "", map_query: "諏訪湖" },
      { period: "09:30", name: "⛩️ 諏訪大社", category: "spot", text: "", map_query: "諏訪大社" },
      { period: "11:30", name: "🚄 JR特急しなの → 名古屋", category: "transport", text: "", map_query: "名古屋駅" },
      { period: "14:00", name: "🛍️ 榮商圈購物", category: "spot", text: "", map_query: "栄 名古屋" },
      { period: "15:30", name: "🌆 綠洲21 Oasis 21", category: "spot", text: "名古屋電視塔夜景", map_query: "オアシス21" },
      { period: "18:30", name: "🍗 名古屋地雞手羽先", category: "food", text: "世界之山 晚餐", map_query: "世界の山ちゃん 名古屋" },
    ],
  },
  {
    id: "day7",
    order_num: 7,
    date: "9/01（二）",
    title: "名古屋市區深度一日遊",
    hotel: "名古屋（第 2 晚）",
    items: [
      { period: "09:00", name: "🏯 名古屋城・本丸御殿", category: "spot", text: "", map_query: "名古屋城" },
      { period: "12:00", name: "⛩️ 熱田神宮", category: "spot", text: "", map_query: "熱田神宮" },
      { period: "14:00", name: "🛒 大須商店街", category: "spot", text: "", map_query: "大須商店街" },
      { period: "18:00", name: "🍜 山本屋総本家 味噌鍋燒烏龍麵", category: "food", text: "晚餐（或矢場豚味噌豬排）", map_query: "山本屋総本家" },
    ],
  },
  {
    id: "day8",
    order_num: 8,
    date: "9/02（三）",
    title: "名古屋最後採買 → 返台",
    hotel: "",
    items: [
      { period: "10:00", name: "🛍️ 名鐵百貨・伴手禮／藥妝", category: "spot", text: "", map_query: "名鉄百貨店 名古屋" },
      { period: "16:00", name: "🚃 名鐵特急 μ-SKY → 機場", category: "transport", text: "", map_query: "中部国際空港" },
      { period: "18:30", name: "🛬 中部國際機場・報到", category: "transport", text: "", map_query: "中部国際空港" },
      { period: "21:00", name: "✈️ 班機起飛 返台", category: "transport", text: "", map_query: "中部国際空港" },
    ],
  },
];
